In [4]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model(r"C:\Users\PC-LAB1\img_processing_lab\day05\data\dogs-vs-cats\train\train\cat.6.jpg")

results[0].show()

for result in results:
    for box in result.boxes:
        print(
            box.xyxy,
            box.conf,
            box.cls
        )



image 1/1 C:\Users\PC-LAB1\img_processing_lab\day05\data\dogs-vs-cats\train\train\cat.6.jpg: 512x640 1 person, 1 cat, 1 couch, 43.4ms
Speed: 2.3ms preprocess, 43.4ms inference, 0.8ms postprocess per image at shape (1, 3, 512, 640)
tensor([[ 61.3328, 119.3508, 185.2827, 230.2799]]) tensor([0.8112]) tensor([15.])
tensor([[ 30.2613,  18.3009, 399.1523, 295.3331]]) tensor([0.7082]) tensor([0.])
tensor([[  1.2254,   3.1622, 396.6479, 293.9233]]) tensor([0.3543]) tensor([57.])


In [5]:
from ultralytics import YOLO
import cv2

model = YOLO("yolo11n.pt")

cap = cv2.VideoCapture(r"C:\Users\PC-LAB1\img_processing_lab\videos\dhaka_traffic.mp4")

while True:
    ret, frame = cap.read()

    if not ret:
        break

    results = model(frame)

    annotated = results[0].plot()

    cv2.imshow("YOLO Detection", annotated)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()



0: 384x640 5 persons, 3 bicycles, 6 cars, 1 motorcycle, 1 truck, 59.5ms
Speed: 1.6ms preprocess, 59.5ms inference, 4.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 bicycle, 4 cars, 1 truck, 64.9ms
Speed: 1.9ms preprocess, 64.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 2 bicycles, 4 cars, 1 motorcycle, 1 truck, 62.6ms
Speed: 1.5ms preprocess, 62.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 bicycles, 4 cars, 1 truck, 59.1ms
Speed: 1.4ms preprocess, 59.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 2 bicycles, 5 cars, 1 truck, 61.6ms
Speed: 1.8ms preprocess, 61.6ms inference, 4.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 3 bicycles, 3 cars, 1 bus, 1 truck, 61.4ms
Speed: 1.9ms preprocess, 61.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 3 bicycl

In [ ]:
import cv2
from ultralytics import YOLO

# Load YOLO model
model = YOLO("yolo11n.pt")

# Open video file
cap = cv2.VideoCapture(r"C:\Users\PC-LAB1\img_processing_lab\videos\dhaka_traffic.mp4")

# COCO Class IDs
CLASS_PERSON = 0
CLASS_CAR = 2
CLASS_MOTORCYCLE = 3
CLASS_BUS = 5

frame_number = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    frame_number += 1

    # Perform detection
    results = model(frame)

    # Annotate frame with standard bounding boxes
    annotated = results[0].plot()

    # Extract detected class IDs
    boxes = results[0].boxes
    if boxes is not None and len(boxes) > 0:
        classes = boxes.cls.cpu().numpy().astype(int)
    else:
        classes = []

    # Count specific target classes
    person_count = (classes == CLASS_PERSON).sum()
    car_count = (classes == CLASS_CAR).sum()
    motorcycle_count = (classes == CLASS_MOTORCYCLE).sum()
    bus_count = (classes == CLASS_BUS).sum()

    # Prepare overlay text lines
    text_lines = [
        f"Frame: {frame_number}",
        f"Cars: {car_count}",
        f"Persons: {person_count}",
        f"Buses: {bus_count}",
        f"Motorcycles: {motorcycle_count}",
    ]

    # Display counts on top left corner
    x, y = 20, 35
    line_height = 30

    for i, line in enumerate(text_lines):
        # Draw dark background outline/shadow for readability
        cv2.putText(
            annotated,
            line,
            (x, y + i * line_height),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 0, 0),
            4,
            cv2.LINE_AA,
        )
        # Draw white foreground text
        cv2.putText(
            annotated,
            line,
            (x, y + i * line_height),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )

    # Show the annotated image
    cv2.imshow("YOLO Detection", annotated)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


0: 384x640 5 persons, 3 bicycles, 6 cars, 1 motorcycle, 1 truck, 55.8ms
Speed: 1.6ms preprocess, 55.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 bicycle, 4 cars, 1 truck, 41.4ms
Speed: 2.5ms preprocess, 41.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 2 bicycles, 4 cars, 1 motorcycle, 1 truck, 31.7ms
Speed: 0.9ms preprocess, 31.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 bicycles, 4 cars, 1 truck, 37.1ms
Speed: 1.9ms preprocess, 37.1ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 2 bicycles, 5 cars, 1 truck, 35.0ms
Speed: 1.0ms preprocess, 35.0ms inference, 0.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 3 bicycles, 3 cars, 1 bus, 1 truck, 37.4ms
Speed: 1.2ms preprocess, 37.4ms inference, 0.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 3 bicycl

: 