In [1]:
import numpy as np

In [2]:
image = np.array([
    [0,50,100],
    [150,200,250],
    [255,128,64]
])

print(image)

[[  0  50 100]
 [150 200 250]
 [255 128  64]]


In [3]:
print("Shape:", image.shape)

Shape: (3, 3)


In [4]:
print("Datatype:", image.dtype)

Datatype: int64


In [5]:
print("Minimum:", image.min())

Minimum: 0


In [6]:
print("Maximum:", image.max())

Maximum: 255


In [7]:
print("Mean:", image.mean())

Mean: 133.0


In [8]:
print(image[2,2])

64


In [9]:
print(image[0,1])

50


In [10]:
print(image[2,0])

255


In [11]:
image[1,1] = 164

In [12]:
print(image)

[[  0  50 100]
 [150 164 250]
 [255 128  64]]


In [13]:
image[0,:]=[32,16,8]

In [14]:
print(image)

[[ 32  16   8]
 [150 164 250]
 [255 128  64]]


In [15]:
image[:,2] = [180,147,93]

In [16]:
print(image)

[[ 32  16 180]
 [150 164 147]
 [255 128  93]]


In [17]:
print("Mean:",image.mean())

Mean: 129.44444444444446
